"""Streamlit dashboard for model scoring and source-grounded RAG assistance."""

from __future__ import annotations

import os
from pathlib import Path
import sys
from typing import Any

import streamlit as st

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
APP_DIR = Path(__file__).resolve().parent
if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))

from model import Predictor
from deep_learning import load_deep_learning_handoff
from dl_inference import DLInferenceError, load_dl_runtime, predict_mlp, score_autoencoder
from rag.assistant import RAGAnswer, RAGAssistant
from rag.retriever import DEFAULT_SOURCES_DIR, SourceRetriever

st.set_page_config(page_title="Industrial Predictive Maintenance", page_icon="🏭", layout="wide")
st.session_state.setdefault("rag_messages", [])


@st.cache_resource
def load_predictor() -> Predictor:
    """Load the versioned artifact once per Streamlit process."""
    return Predictor()


@st.cache_resource
def load_retriever() -> SourceRetriever:
    """Build the local source index once per Streamlit process."""
    return SourceRetriever(DEFAULT_SOURCES_DIR)


@st.cache_resource
def load_dl_runtime_cached():
    """Attempt to actually load the MLP/autoencoder once per Streamlit process.

    Unlike load_deep_learning_handoff(), this tries to load and prepare the
    real Keras models for inference, not just check that files exist.
    """
    return load_dl_runtime()


def configured_groq_api_key() -> str | None:
    """Read a key from the environment or Streamlit secrets without displaying it."""
    if os.getenv("RAG_RETRIEVAL_ONLY") == "1":
        return None
    if os.getenv("GROQ_API_KEY"):
        return os.environ["GROQ_API_KEY"]
    try:
        key = st.secrets.get("GROQ_API_KEY")
    except (FileNotFoundError, KeyError):
        key = None
    return str(key) if key else None


def current_prediction_context() -> dict[str, Any] | None:
    """Expose the latest project prediction to the RAG assistant as context only."""
    result = st.session_state.get("latest_prediction")
    inputs = st.session_state.get("latest_inputs")
    if not result:
        return None
    context: dict[str, Any] = {
        "model": result["model_name"],
        "failure probability": f"{result['failure_probability']:.2%}",
        "decision threshold": f"{result['threshold']:.3f}",
        "project classification": result["status"],
    }
    if inputs:
        context.update({f"input - {key}": value for key, value in inputs.items()})
    return context


def show_sources(answer: RAGAnswer) -> None:
    """Render source labels generated by local retrieval, not by the language model."""
    if not answer.sources:
        return
    seen: set[str] = set()
    st.caption("Sources retrieved from the project knowledge base")
    for result in answer.sources:
        citation = result.chunk.citation
        if citation not in seen:
            st.markdown(f"- `{citation}`")
            seen.add(citation)


st.title("🏭 Industrial Predictive Maintenance")
st.caption("Model scoring and a source-grounded assistant for the synthetic AI4I project benchmark.")

try:
    predictor = load_predictor()
    retriever = load_retriever()
except Exception as exc:
    st.error(f"Application setup failed: {exc}")
    st.stop()

groq_api_key = configured_groq_api_key()
assistant = RAGAssistant(retriever=retriever, groq_api_key=groq_api_key)

with st.sidebar:
    st.header("Assistant status")
    if groq_api_key:
        st.success(f"Generated answers enabled with `{assistant.model}`.")
    else:
        st.info("Retrieval-only mode. Set `GROQ_API_KEY` or Streamlit secrets to enable generated answers.")
    st.caption(f"Local corpus: {len(retriever.chunks)} source chunks")
    st.caption("AI4I is synthetic. Follow approved site procedures for real equipment.")

prediction_tab, deep_learning_tab, assistant_tab, sources_tab = st.tabs(
    ["Predict risk", "Deep Learning", "Maintenance assistant", "Knowledge base"]
)

with prediction_tab:
    st.subheader("Estimate project failure risk")
    st.caption(f"Saved model: {predictor.model_name}. A score is not a confirmed diagnosis.")
    with st.form("prediction_form"):
        left, right = st.columns(2)
        with left:
            type_value = st.selectbox("Product type", ["L", "M", "H"])
            air_temp = st.number_input("Air temperature [K]", min_value=0.0, value=300.0)
            process_temp = st.number_input("Process temperature [K]", min_value=0.0, value=310.0)
        with right:
            rotational_speed = st.number_input("Rotational speed [rpm]", min_value=0.0, value=1500.0)
            torque = st.number_input("Torque [Nm]", min_value=0.0, value=40.0)
            tool_wear = st.number_input("Tool wear [min]", min_value=0.0, value=100.0)
        submitted = st.form_submit_button("Estimate risk", type="primary")

    if submitted:
        inputs = {
            "Type": type_value,
            "Air temperature [K]": air_temp,
            "Process temperature [K]": process_temp,
            "Rotational speed [rpm]": rotational_speed,
            "Torque [Nm]": torque,
            "Tool wear [min]": tool_wear,
        }
        try:
            result = predictor.predict(inputs)
        except Exception as exc:
            st.error(f"Prediction could not be generated: {exc}")
        else:
            st.session_state["latest_prediction"] = result
            st.session_state["latest_inputs"] = inputs
            metric, threshold_metric, status_metric = st.columns(3)
            metric.metric("Failure probability", f"{result['failure_probability']:.2%}")
            threshold_metric.metric("Decision threshold", f"{result['threshold']:.3f}")
            status_metric.metric("Project classification", result["status"])
            if result["failure_prediction"]:
                st.warning("The project model estimates elevated risk. This is not a confirmed diagnosis.")
            else:
                st.success("The project model estimates risk below its saved threshold.")
            st.info("Ask the Maintenance assistant to explain the AI4I context for this result.")

with deep_learning_tab:
    st.subheader("Deep Learning models")
    mlp_runtime, autoencoder_runtime = load_dl_runtime_cached()
    both_ready = mlp_runtime.ready and autoencoder_runtime.ready

    with st.expander("Handoff status", expanded=not both_ready):
        st.caption("File-level checks only: required metadata present and artifact files exist.")
        mlp_handoff, autoencoder_handoff = load_deep_learning_handoff()
        for handoff in (mlp_handoff, autoencoder_handoff):
            with st.container(border=True):
                if handoff.ready:
                    st.success(f"{handoff.name} handoff is ready for inference integration.")
                    st.caption(
                        f"Framework: {handoff.metadata['framework']} | "
                        f"Features: {len(handoff.metadata['feature_order'])}"
                    )
                    if handoff.name == "MLP":
                        st.metric("MLP decision threshold", handoff.metadata["decision_threshold"])
                    else:
                        st.metric("Autoencoder anomaly threshold", handoff.metadata["anomaly_threshold"])
                else:
                    st.info(f"{handoff.name}: awaiting a complete model handoff.")
                    for message in handoff.messages:
                        st.caption(message)
        st.caption("Handoff contract: `models/deep_learning/README.md`")

    if not (mlp_runtime.ready or autoencoder_runtime.ready):
        st.info("Awaiting the real MLP and autoencoder artifacts before this panel can run predictions.")
        for runtime in (mlp_runtime, autoencoder_runtime):
            for message in runtime.messages:
                st.error(f"**{runtime.name} Loading Error:** {message}")
    else:
        st.caption(
            "Runs the actual loaded Keras models. Estimates from the synthetic AI4I benchmark -- "
            "not a confirmed equipment diagnosis."
        )
        for runtime in (mlp_runtime, autoencoder_runtime):
            if not runtime.ready:
                st.warning(f"{runtime.name} could not be loaded for inference: {'; '.join(runtime.messages)}")

        with st.form("dl_prediction_form"):
            left, right = st.columns(2)
            with left:
                dl_type = st.selectbox("Product type", ["L", "M", "H"], key="dl_type")
                dl_air_temp = st.number_input("Air temperature [K]", min_value=0.0, value=300.0, key="dl_air")
                dl_process_temp = st.number_input(
                    "Process temperature [K]", min_value=0.0, value=310.0, key="dl_process"
                )
            with right:
                dl_speed = st.number_input("Rotational speed [rpm]", min_value=0.0, value=1500.0, key="dl_speed")
                dl_torque = st.number_input("Torque [Nm]", min_value=0.0, value=40.0, key="dl_torque")
                dl_wear = st.number_input("Tool wear [min]", min_value=0.0, value=100.0, key="dl_wear")
            dl_submitted = st.form_submit_button("Run deep-learning models", type="primary")

        if dl_submitted:
            dl_inputs = {
                "Type": dl_type,
                "Air temperature [K]": dl_air_temp,
                "Process temperature [K]": dl_process_temp,
                "Rotational speed [rpm]": dl_speed,
                "Torque [Nm]": dl_torque,
                "Tool wear [min]": dl_wear,
            }

            mlp_col, ae_col = st.columns(2)
            with mlp_col:
                st.markdown("**MLP -- failure classification**")
                if mlp_runtime.ready:
                    try:
                        mlp_result = predict_mlp(mlp_runtime.model, dl_inputs)
                    except DLInferenceError as exc:
                        st.error(f"MLP inference failed: {exc}")
                    else:
                        st.metric("Failure probability", f"{mlp_result['failure_probability']:.2%}")
                        st.metric("Decision threshold", f"{mlp_result['threshold']:.3f}")
                        st.metric("Classification", mlp_result["status"])
                else:
                    st.info("MLP is not available for inference yet.")
            with ae_col:
                st.markdown("**Autoencoder -- anomaly score**")
                if autoencoder_runtime.ready:
                    try:
                        ae_result = score_autoencoder(autoencoder_runtime.model, dl_inputs)
                    except DLInferenceError as exc:
                        st.error(f"Autoencoder inference failed: {exc}")
                    else:
                        st.metric("Reconstruction error", f"{ae_result['reconstruction_error']:.4f}")
                        if ae_result["anomaly_threshold"] is not None:
                            st.metric("Anomaly threshold", f"{float(ae_result['anomaly_threshold']):.4f}")
                            st.metric("Anomalous?", "Yes" if ae_result["is_anomaly"] else "No")
                        else:
                            st.caption("No anomaly threshold set yet; showing raw reconstruction error only.")
                else:
                    st.info("Autoencoder is not available for inference yet.")

            st.caption(
                "Failure probability, classification decision, and anomaly score are distinct signals -- "
                "compare them, and with the classical-model tab, rather than treating any single one as final."
            )

with assistant_tab:
    st.subheader("Ask the project maintenance assistant")
    st.caption("Answers are grounded in the local RAG corpus and show the retrieved sources.")
    for message in st.session_state.rag_messages:
        with st.chat_message(message["role"]):
            st.markdown(message["text"])
            if message["role"] == "assistant":
                show_sources(message["answer"])
                if message["answer"].warning:
                    st.caption(message["answer"].warning)

    question = st.chat_input(
        "Example: What does HDF mean in this project?",
        key="rag_question",
        submit_mode="disable",
    )
    if question:
        st.session_state.rag_messages.append({"role": "user", "text": question})
        with st.chat_message("user"):
            st.markdown(question)
        with st.chat_message("assistant"):
            with st.spinner("Retrieving project sources..."):
                answer = assistant.answer(question, prediction_context=current_prediction_context())
            st.markdown(answer.text)
            show_sources(answer)
            if answer.warning:
                st.caption(answer.warning)
        st.session_state.rag_messages.append(
            {"role": "assistant", "text": answer.text, "answer": answer}
        )

with sources_tab:
    st.subheader("Indexed project sources")
    st.caption("Only curated Markdown files in `rag/sources` are indexed.")
    for path in sorted(DEFAULT_SOURCES_DIR.glob("*.md")):
        with st.expander(path.name):
            st.markdown(path.read_text(encoding="utf-8"))